### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [KevinB1500/ISII-WORKSHOPS-WEB_CENTROS_DE_INVESTIGACION#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by kdbautis** [comment]
We will begin the request implementation process, @gabicuadros will perform the Impact Analysis, @KevinB1500 will perform the development of the solution and @Kfyepez  will perform the tests.

**Comment by kdbautis** [comment]
The request hasn't been implemented yet, so we will proceed to implement it.

**Comment by kdbautis** [comment]
The request has been analyzed, it will be categorized has an enhancement

**Comment by jose598** [comment]
@KevinB1500 Got it

**Comment by gabicuadros** [comment]
Hi @jose598, this is our impact analysis, please review it
thank you 

[Impact Analysis.docx](https://github.com/KevinB1500/ISII-WORKSHOPS-WEB_CENTROS_DE_INVESTIGACION/files/7917606/Impact.Analysis.docx)

**Comment by jose598** [comment]
Ok, it sounds good.
Continue with the next step

**Comment by jose598** [comment]
Are you still working on the issue? @gabicuadros @Kfyepez @KevinB1500

**Comment by kdbautis** [comment]
Hi @jose598, attending the request #1, the new commit and branch with the implementation of the functions requested has been implemented. 
https://github.com/KevinB1500/ISII-WORKSHOPS-WEB_CENTROS_DE_INVESTIGACION/blob/486f985f9ef69de421aadaba8c27d0bc13e4faaf/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/Insurance.java#L30-L45

**Comment by jose598** [comment]
OK, please make the test plan!

**Comment by Kfyepez** [comment]
Hi @jose598, here is attached the test plan with all the tests necessary to run each function passed.
[Test Plan.docx](https://github.com/KevinB1500/ISII-WORKSHOPS-WEB_CENTROS_DE_INVESTIGACION/files/7917682/Test.Plan.docx)

**Comment by jose598** [comment]
@Kfyepez Got it!
Please continue with the next step

**Comment by Kfyepez** [comment]
Hi @jose598, finally here is the acceptance testing, let us know if you agree with it, thank you
[Acceptance testing.docx](https://github.com/KevinB1500/ISII-WORKSHOPS-WEB_CENTROS_DE_INVESTIGACION/files/7917688/Acceptance.testing.docx)

**Comment by jose598** [comment]
I agree

**Comment by Kfyepez** [comment]
Thanks @jose598, the new version of the software will be released by @KevinB1500

**Comment by kdbautis** [comment]
Thank you @jose598, the new version of the software is ready to be used.
In order to use it you will need:

1. Java 11 and git installed
2. An IDE for running the software
3. Clone the Issues Management branch from cmd. 
`git clone --branch IssuesManagement https://github.com/KevinB1500/ISII-WORKSHOPS-WEB_CENTROS_DE_INVESTIGACION.git`
4. Open and run the application.

**Comment by kdbautis** [comment]
@jose598 Were you able to use the software? If so, tell us if you're satisfied with the solution please, thank you

**Comment by jose598** [comment]
Yes, I am satisfied with the soft solution. @KevinB1500 

Close the issue please
